# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_a1:
    has_velocity_limits: true
    max_velocity: 3.83972
    has_acceleration_limits: true
    max_acceleration: 0.734
    has_jerk_limits: false
  joint_a2:
    has_velocity_limits: true
    max_velocity: 3.66519
    has_acceleration_limits: true
    max_acceleration: 0.664
    has_jerk_limits: false
  joint_a3:
    has_velocity_limits: true
    max_velocity: 4.71239
    has_acceleration_limits: true
    max_acceleration: 0.734
    has_jerk_limits: false
  joint_a4:
    has_velocity_limits: true
    max_velocity: 6.6497
    has_acceleration_limits: true
    max_acceleration: 1.396
    has_jerk_limits: false
  joint_a5:
    has_velocity_limits: true
    max_velocity: 5.42797
    has_acceleration_limits: true
    max_acceleration: 1.396
    has_jerk_limits: false
  joint_a6:
    has_velocity_limits: true
    max_velocity: 8.23795
    has_acceleration_limits: true
    max_acceleration: 2.094
    has_jerk_limits: false
  flange-tool0:
    has_velocity_limits: true
    max_velocity: 8.23795
    has_acceleration_limits: true
    max_acceleration: 2.094
    has_jerk_limits: false
  