controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    calvary_joint_trajectory_soft_stoppable_controller:
      type: calvary_joint_trajectory_soft_stoppable_controller/CalvaryJointTrajectorySoftStoppableController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    # configure_components_on_start: [""]
